# Generated by Django 5.2.12 on 2026-04-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('math', 'Mathematics'), ('physics', 'Physics'), ('bio', 'Biology'), ('Mlt', 'Multiple')], default='Mlt', max_length=100),
        ),
    ]
