# Generated by Django 5.2.12 on 2026-04-06 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course_code', models.CharField(help_text='e.g., PHY-101, CS-202', max_length=20, unique=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('credits', models.PositiveIntegerField(default=3, help_text='Number of credit hours')),
                ('semester', models.PositiveIntegerField(blank=True, help_text='Semester :1, 2, 3...', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_course', to='teacher.teacher')),
            ],
        ),
    ]
