# Generated by Django 5.2.12 on 2026-04-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, choices=[('cs', 'Computer Science'), ('math', 'Mathematics'), ('physics', 'Physics'), ('bio', 'Biology'), ('Mlt', 'Multiple')], max_length=100, null=True),
        ),
    ]
