# Generated by Django 5.2.12 on 2026-04-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.PositiveIntegerField(blank=True, help_text='Semester :1, 2, 3...', null=True),
        ),
    ]
